### ISSUE TITLE
Function not implemented, linux-clear 5.1.3

### ISSUE THREAD

**Issue by jjo148** [linuxdeepin/deepin-anything#20]
Running kernel 5.1.3-1-clear-current and can't load the vfs_monitor module, it apparently loads and works on the standard arch linux kernel.

`systemd-modules-load[547]: Failed to insert module 'vfs_monitor': Function not implemented`

dmesg output:
```
[  +0.000003] register_kretprobes failed, returned -38
[  +0.000003] register_kretprobes failed, returned -38
[  +0.000011] register_kretprobes failed, returned -38
[  +0.000003] register_kretprobes failed, returned -38
```

**Comment by felixonmars** [comment]
Which version of deepin-anything are you using? It works fine here with https://github.com/linuxdeepin/deepin-anything/pull/18

**Comment by jjo148** [comment]
> Which version of deepin-anything are you using? It works fine here with #18

I am using deepin-anything version 0.1.0-2, and the kernel from [http://download.opensuse.org/repositories/home:/metakcahura:/kernel/Arch_Extra_standard/x86_64/](url)
This problem seems to be isolated to the linux-clear kernel as linux-ck, linux-rt and linux-arch does not print these errors.

**Comment by jjo148** [comment]
Still present in Linux kernel 5.2.4-1-clear

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
