### ISSUE TITLE
deepin-anything-monitor.service不停的自动重启

### ISSUE THREAD

**Issue by qcxiang** [linuxdeepin/deepin-anything#32]
全新安装的deepin 20.1 社区版
/(根分区ext4格式)
内核版本Linux 5.8.14-amd64-desktop

**错误日志如下：**

daemon.log:Jan  4 17:30:14 mgdev systemd[1]: deepin-anything-monitor.service: Service RestartSec=10s expired, scheduling restart.
daemon.log:Jan  4 17:30:14 mgdev systemd[1]: deepin-anything-monitor.service: Scheduled restart job, restart counter is at 394.
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.537] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::DASPluginLoaderPrivate: 97]: plugin paths: ("/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins")
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.537] [default-debug] [deepin_anything_server::DASPluginLoader::DASPluginLoader: 336]: watch: "/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers"
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.537] [default-debug] [deepin_anything_server::DASPluginLoader::update: 365]: PluginLoader::PluginLoader() checking directory path "/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers" ...
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.537] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::loadPlugin: 150]: PluginLoader::PluginLoader() looking at "/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers/libdde-anythingmonitor.so"
**daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.541] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::loadPlugin: 157]: "Cannot load library /usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers/libdde-anythingmonitor.so: (/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers/libdde-anythingmonitor.so: undefined symbol: _ZN26ComDeepinAnythingInterfaceC1ERK7QStringS2_RK15QDBusConnectionP7QObject)"**
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.541] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::loadPlugin: 150]: PluginLoader::PluginLoader() looking at "/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers/libupdate-lft.so"
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.542] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::loadPlugin: 167]: Got keys from plugin meta data ("update-lft")
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.542] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::loadPlugin: 210]: file last modified: QDateTime(2020-07-09 21:45:14.000 CST Qt::TimeSpec(LocalTime))
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.542] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::loadPlugin: 150]: PluginLoader::PluginLoader() looking at "/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers/README.txt"
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.542] [default-debug] [deepin_anything_server::DASPluginLoaderPrivate::loadPlugin: 157]: "'/usr/lib/x86_64-linux-gnu/deepin-anything-server-lib/plugins/handlers/README.txt' is not an ELF object"
daemon.log:Jan  4 17:30:14 mgdev deepin-anything-monitor[20053]: [2021-01-04, 17:30:14.546] [default-critical] [deepin_anything_server::Server::run: 179]: Failed on wait data "对设备不适当的 ioctl 操作"
daemon.log:Jan  4 17:30:14 mgdev systemd[1]: deepin-anything-monitor.service: Main process exited, code=exited, status=25/n/a
daemon.log:Jan  4 17:30:14 mgdev systemd[1]: deepin-anything-monitor.service: Failed with result 'exit-code'.

**Comment by deepin-CD** [comment]
At my computer(X86 AMD64),This problem did not appear.Did you do anything else？How did this happen？

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
