### ISSUE TITLE
unable to build deepin-anything package

### ISSUE THREAD

**Issue by espacelovesongs** [linuxdeepin/deepin-anything#33]
Kindly refer to the following build error
------------------------------
DKMS make.log for deepin-anything-0.0 for kernel 5.8.0-36-generic (x86_64)
Mon 11 Jan 2021 22:34:29 AEDT
make: Entering directory '/usr/src/linux-headers-5.8.0-36-generic'
  CC [M]  /var/lib/dkms/deepin-anything/0.0/build/vfs_utils.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0/build/arg_extractor.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0/build/vfs_change.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0/build/vfs_kretprobes.o
/var/lib/dkms/deepin-anything/0.0/build/vfs_change.c: In function ‘copy_vfs_changes’:
/var/lib/dkms/deepin-anything/0.0/build/vfs_change.c:128:3: error: unknown type name ‘time_t’; did you mean ‘ktime_t’?
  128 |   time_t shifted_secs = vc->ts.tv_sec + hour_shift*3600;
      |   ^~~~~~
      |   ktime_t
/var/lib/dkms/deepin-anything/0.0/build/vfs_change.c: In function ‘init_vfs_changes’:
/var/lib/dkms/deepin-anything/0.0/build/vfs_change.c:348:74: error: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  348 |  struct proc_dir_entry* procfs_entry = proc_create(PROCFS_NAME, 0666, 0, &procfs_ops);
      |                                                                          ^~~~~~~~~~~
      |                                                                          |
      |                                                                          struct file_operations *
In file included from /var/lib/dkms/deepin-anything/0.0/build/vfs_change.c:5:
./include/linux/proc_fs.h:107:24: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
  107 | struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
      |                        ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:288: /var/lib/dkms/deepin-anything/0.0/build/vfs_change.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1780: /var/lib/dkms/deepin-anything/0.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.8.0-36-generic'

**Comment by deepin-CD** [comment]
你的deepin-anything版本太旧了，重新下载deepin-anything最新代码就可以使用了，具体的
![image](https://user-images.githubusercontent.com/70992023/104979471-50cd3f80-5a3f-11eb-8e80-597096fbb114.png)
