### ISSUE TITLE
System startup failure

### ISSUE THREAD

**Issue by mkdir700** [linuxdeepin/deepin-anything#42]
Deepin Version：20.3

问题描述：
电脑开机后，一直输出这句话。无法进入tty。

问题截图：
![image](https://user-images.githubusercontent.com/56359329/149652256-a9be7542-10be-4b0b-99d5-3c70bb3fa214.png)

定位输出此日志：
https://github.com/linuxdeepin/deepin-anything/blob/afb0508d0e5b8340c73d849fadc17d00432163b0/kernelmod/vfs_kretprobes.c#L138

**Comment by wangrong1069** [comment]
该日志表示，deepin-anything 监视文件系统挂载出现异常
多次出现该日志，说明系统正在多次挂载文件系统，可能不断失败不断重试中
建议1，查看系统中更详细的日志，如 syslog
建议2，删除系统中的 /etc/systemd/system/multi-user.target.wants/deepin-anything-monitor.service 文件，以禁止 deepin-anything 监视部分的启动，这样就不会再打印该日志了，用以排查是否是 deepin-anything 的问题
至于如何查看和修改系统中的文件，可以考虑先通过其他系统启动，然后挂载问题系统的相关分区

**Comment by mkdir700** [comment]
> 该日志表示，deepin-anything 监视文件系统挂载出现异常 多次出现该日志，说明系统正在多次挂载文件系统，可能不断失败不断重试中 建议1，查看系统中更详细的日志，如 syslog 建议2，删除系统中的 /etc/systemd/system/multi-user.target.wants/deepin-anything-monitor.service 文件，以禁止 deepin-anything 监视部分的启动，这样就不会再打印该日志了，用以排查是否是 deepin-anything 的问题 至于如何查看和修改系统中的文件，可以考虑先通过其他系统启动，然后挂载问题系统的相关分区

感谢您的回复。

我关闭`deepin-anything-monitor.service`服务后

查看`auth.log`授权日志，发现很多文件已找不到，我猜测是因为这些文件丢失的缘故导致系统无法开启。

![image](https://user-images.githubusercontent.com/56359329/149654008-cb915649-6a9c-45f3-af13-9203472fa3a2.png)

**Comment by wangrong1069** [comment]
不客气哈，这是我们应该做的
遇到这种情况，可以尝试从正常系统中拷贝缺失的文件

**Comment by mkdir700** [comment]
> 不客气哈，这是我们应该做的 遇到这种情况，可以尝试从正常系统中拷贝缺失的文件

我目前正在使用windows系统，准备使用diskgenius把文件拷贝进去，但是免费版不支持此功能。

请教下，您知道有什么办法进行文件拷贝吗？谢谢👍

**Comment by wangrong1069** [comment]
可以参考如下方法
方法：使用 live 系统启动，并拷贝其上的文件
步骤：
1. 制作一个 deepin USB 启动盘
2. 通过 USB 启动系统，并进入安装界面
3. 进入 tty2
4. 挂载问题系统上相应的分区
5. 拷贝缺失文件

**Comment by mkdir700** [comment]
> 可以参考如下方法 方法：使用 live 系统启动，并拷贝其上的文件 步骤：
> 
> 1. 制作一个 deepin USB 启动盘
> 2. 通过 USB 启动系统，并进入安装界面
> 3. 进入 tty2
> 4. 挂载问题系统上相应的分区
> 5. 拷贝缺失文件

好的，谢谢🙂
