### ISSUE TITLE
No external kernel module in Fedora

### ISSUE THREAD

**Issue by 1dot75cm** [linuxdeepin/deepin-anything#5]
> No External Kernel Modules
>
> At one point (pre Fedora 8), packages containing "addon" kernel modules were permitted. This is no longer the case. Fedora strongly encourages kernel module packagers to submit their code into the upstream kernel tree. 

https://fedoraproject.org/wiki/Packaging:Guidelines#No_External_Kernel_Modules

Maybe we can use other ways to instead of `vfs_monitor` kernel module.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
