### ISSUE TITLE
Upgrade to 15.8 Issue

### ISSUE THREAD

**Issue by rizmut** [linuxdeepin/deepin-anything#7]
I don't know which component should be opened for this issue. I've encounter dpkg/apt stucked when trying to upgrade from 15.7 to 15.8. Here the output:

`Processing triggers for initramfs-tools (0.130) ...
update-initramfs: Generating /boot/initrd.img-4.15.0-29deepin-generic
WARNING: Setting CRYPTSETUP in /etc/initramfs-tools/initramfs.conf is deprecated and will stop working in the future. Use /etc/cryptsetup-initramfs/conf-hook instead.
setupcon is missing. Please install the 'console-setup' package.
W: plymouth: The plugin label.so is missing, the selected theme might not work as expected.
W: plymouth: You might want to install the plymouth-themes package to fix this.
I: The initramfs will attempt to resume from /dev/sda4
I: (UUID=5e12afb9-77f8-4fd7-b2a4-8e62c29ac951)
I: Set the RESUME variable to override this.
dpkg: unrecoverable fatal error, aborting:
 gagal memasang status terbaru dari 'initramfs-tools': Tidak ada berkas atau direktori seperti itu
`

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
