### ISSUE TITLE
What is `deepin-anything-server`? How to use?

### ISSUE THREAD

**Issue by bryango** [linuxdeepin/deepin-anything#8]
This project seems awesome, but I am not sure how to use it... :joy: 
```text
### platform: manjaro (Arch like) + GNOME desktop
```
Is this just a kernel module? Seems that I have successfully installed it: 
```text
$ lsmod | grep vfs
vfs_monitor            24576  0

$ cat /proc/vfs_changes | tail -n 3
2018-11-19 21:31:10.725 file-created /home/bryan/.config/google-chrome/Default/Preferences
2018-11-19 21:31:14.005 file-created /home/bryan/.cache/clipboard-indicator@tudmotu.com/registry.txt
2018-11-19 21:31:45.220 file-created /home/bryan/.config/google-chrome/Default/Preferences
```
However, there is a executable called `deepin-anything-server` and a corresponding `.service` file, which is not automatically enabled:
```text
$ systemctl status deepin-anything-server.service 
● deepin-anything-server.service - Deepin anything service
   Loaded: loaded (/usr/lib/systemd/system/deepin-anything-server.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```
Should I enable it for `deepin-anything` to function properly? Thanks!

P. S. to deepin developers: 
这么好的东西，感觉可以多宣传一些 <img src="https://bryango.github.io/assets/coolemoji/tieba_emotion_25.png" alt="" width="24px">
百度了一下，感觉国内相关的介绍也寥寥无几，只有[这里](https://bbs.deepin.org/forum.php?mod=viewthread&tid=158373)有点信息，但也不多...

**Comment by zccrs** [comment]
关于使用方面，忙完这一阵我会写个简单的文档

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
